# Generated by Django 5.2.4 on 2025-07-11 02:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_ficha_customuser_ficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='docentes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'docente'}, related_name='fichas_dictadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
