# Generated by Django 5.2.4 on 2025-08-14 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_ficha_docentes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('docente', models.ForeignKey(blank=True, limit_choices_to={'role': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_dictadas', to=settings.AUTH_USER_MODEL)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='users.ficha')),
            ],
        ),
    ]
