# Generated by Django 5.2.4 on 2025-08-14 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='materia',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'estudiante'}, related_name='materias_inscritas', to=settings.AUTH_USER_MODEL),
        ),
    ]
