# Generated by Django 5.2.4 on 2025-10-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0003_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
