# Generated by Django 5.2.4 on 2025-10-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_institucion_creado_por_institucion_descripcion'),
        ('materias', '0005_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='instituciones.institucion'),
        ),
    ]
