# Generated by Django 5.1.6 on 2025-09-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='docente',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
