# Generated by Django 5.2.4 on 2025-09-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('politica_retencion', models.TextField(blank=True, null=True)),
                ('asignacion_grupo', models.CharField(choices=[('fichas', 'Fichas (SENA)'), ('grados', 'Grados (Colegio)'), ('carreras', 'Carreras (Universidad)'), ('grupos', 'Grupos'), ('otros', 'Otros')], default='grupos', max_length=20)),
                ('asignacion_materia', models.CharField(choices=[('materias', 'Materias'), ('asignaturas', 'Asignaturas'), ('modulos', 'Módulos'), ('cursos', 'Cursos'), ('otros', 'Otros')], default='materias', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
