# Generated by Django 5.2.4 on 2025-10-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_institucion_creado_por_institucion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='asignacion_materia',
            field=models.CharField(choices=[('materias', 'Materias'), ('asignaturas', 'Asignaturas'), ('modulos', 'Módulos'), ('cursos', 'Cursos'), ('competencia', 'Competencia'), ('otros', 'Otros')], default='materias', max_length=20),
        ),
    ]
